def set_stylesheet():
	return('#centralWidget {\n'
           'background: #232532;\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#menu_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#menu_button {\n'
           'text-align:center;\n'
           'font: 20px;\n'
           'color: #FFFFFF;\n'
           'background-color: #232532;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'max-width:40px;\n'
           'max-height:40px;\n'
           'min-width:40px;\n'
           'min-height:40px;\n'
           '}\n'
           '\n'
           '#menu_frame QPushButton:hover {\n'
           'color: #59F3D7;\n'
           '}\n'
           '\n'
           '#generate_frame {\n'
           'border: None;\n'
           '}\n'
           '\n'
           '#generate_button {\n'
           'text-align:center;\n'
           'font: 18px;\n'
           'color: #FFFFFF;\n'
           'border-style: solid;\n'
           'border-width: 0px;\n'
           'border-radius: 25px;\n'
           'max-width:100px;\n'
           'max-height:50px;\n'
           'min-width:100px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           '#generate_button:hover {\n'
           'color: #59F3D7;\n'
           '}\n'
           '\n'
           '#spacer_frame {\n'
           'border: None;\n'
           'max-width:250px;\n'
           'max-height:50px;\n'
           'min-width:225px;\n'
           'min-height:50px;\n'
           '}\n'
           '\n'
           'QLabel {\n'
           'color: #FFFFFF;\n'
           'font: 18px;\n'
           'max-height:20px;\n'
           'min-height:20px;\n'
           '}\n'
           '\n'
           '\n'
           '')